# scratch/test_post_hitl_reset.py
import pytest

def _evaluate_plan_reset(current_plan: list, command_response: dict, consecutive_failures: int) -> list:
    """
    Evaluates if the LLM action plan queue should be flushed based on execution state.
    We will inject this into local_webai_server_guided.py to safely manage the queue.
    """
    is_success = command_response.get("success", False)
    
    # 1. If we just hit the failure threshold, the current plan is doomed. Flush it.
    if consecutive_failures >= 2:
        return []
        
    # 2. If a HITL interaction successfully resolved (e.g., human clicked and navigated),
    # the DOM has changed. The old cached coordinates/actions are stale. Flush it.
    if is_success and command_response.get("hitl_resolved", False):
        return []
        
    # 3. Otherwise, keep executing the current plan
    return current_plan

def test_plan_retained_on_normal_success():
    plan = [{"action": "clickLocation", "x": 100, "y": 200}, {"action": "wait"}]
    response = {"success": True}
    
    new_plan = _evaluate_plan_reset(plan, response, consecutive_failures=0)
    assert len(new_plan) == 2, "Queue should remain intact after a normal, successful action."

def test_plan_flushed_on_hitl_resolution():
    plan = [{"action": "clickLocation", "x": 904, "y": 365}, {"action": "wait"}]
    # Simulating the response generated by webai_playwright/ai.py after human intervenes
    response = {"success": True, "hitl_resolved": True}
    
    new_plan = _evaluate_plan_reset(plan, response, consecutive_failures=0)
    assert len(new_plan) == 0, "Queue MUST be flushed after a HITL resolution to force a fresh DOM snapshot."

def test_plan_flushed_on_max_failures():
    plan = [{"action": "clickByText", "text": "Buy Now"}]
    response = {"success": False, "error": "Element not found"}
    
    new_plan = _evaluate_plan_reset(plan, response, consecutive_failures=2)
    assert len(new_plan) == 0, "Queue MUST be flushed when failures reach the HITL threshold."