# Generated by Django 5.0.14 on 2025-06-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatmessage_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="user",
            new_name="users",
        ),
    ]
