# Generated by Django 5.0.14 on 2025-06-15 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_rename_user_chatmessage_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="users",
            new_name="user",
        ),
    ]
